-- MySQL Script generated by MySQL Workbench
-- Ter 30 Out 2018 08:54:33 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sara` DEFAULT CHARACTER SET utf8 ;
USE `sara` ;

-- -----------------------------------------------------
-- Table `sara`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `classe` VARCHAR(15) NOT NULL,
  `passageiroOuCargueiro` VARCHAR(9) NOT NULL,
  `especificacao` VARCHAR(10) NOT NULL,
  `Categoriacol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara`.`TipoAeronave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`TipoAeronave` (
  `idTipoAeronave` INT NOT NULL AUTO_INCREMENT,
  `equipamento` VARCHAR(10) NOT NULL,
  `comprimento` FLOAT NOT NULL,
  `envergadura` FLOAT NOT NULL,
  `pmd` FLOAT NULL,
  PRIMARY KEY (`idTipoAeronave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Aeronave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Aeronave` (
  `idAeronave` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(6) NOT NULL,
  `tipoAsa` VARCHAR(5) NOT NULL,
  `TipoAeronave_idTipoAeronave` INT NOT NULL,
  PRIMARY KEY (`idAeronave`, `TipoAeronave_idTipoAeronave`),
  INDEX `fk_Aeronave_TipoAeronave1_idx` (`TipoAeronave_idTipoAeronave` ASC),
  CONSTRAINT `fk_Aeronave_TipoAeronave1`
    FOREIGN KEY (`TipoAeronave_idTipoAeronave`)
    REFERENCES `sara`.`TipoAeronave` (`idTipoAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`OcorrenciaVoo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`OcorrenciaVoo` (
  `idOcorrenciaVoo` INT NOT NULL,
  `data` DECIMAL(10,0) NULL,
  `hora` DECIMAL(10,0) NULL,
  `Aeronave_idAeronave` INT NOT NULL,
  PRIMARY KEY (`idOcorrenciaVoo`),
  INDEX `fk_OcorrenciaVoo_Aeronave1_idx` (`Aeronave_idAeronave` ASC),
  CONSTRAINT `fk_OcorrenciaVoo_Aeronave1`
    FOREIGN KEY (`Aeronave_idAeronave`)
    REFERENCES `sara`.`Aeronave` (`idAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Voo` (
  `idVoo` INT NOT NULL AUTO_INCREMENT,
  `dataPrevistaPouso` DECIMAL(10,0) NULL,
  `horaPrevistaPouso` DECIMAL(10,0) NULL,
  `dataPrevistaDecolagem` DECIMAL(10,0) NULL,
  `horaPrevistaDecolagem` DECIMAL(10,0) NULL,
  `situacao` VARCHAR(15) NOT NULL,
  `origem` VARCHAR(25) NOT NULL,
  `destino` VARCHAR(25) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `OcorrenciaVoo_idOcorrenciaVoo` INT NOT NULL,
  PRIMARY KEY (`idVoo`),
  INDEX `fk_Voo_Categoria_idx` (`Categoria_idCategoria` ASC),
  INDEX `fk_Voo_OcorrenciaVoo1_idx` (`OcorrenciaVoo_idOcorrenciaVoo` ASC),
  CONSTRAINT `fk_Voo_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `sara`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_OcorrenciaVoo1`
    FOREIGN KEY (`OcorrenciaVoo_idOcorrenciaVoo`)
    REFERENCES `sara`.`OcorrenciaVoo` (`idOcorrenciaVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara`.`Movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Movimento` (
  `idMovimento` INT NOT NULL AUTO_INCREMENT,
  `tipoMovimento` VARCHAR(2) NOT NULL,
  `dataMovimento` VARCHAR(10) NOT NULL,
  `horaMovimento` DECIMAL(10,0) NOT NULL,
  `OcorrenciaVoo_idOcorrenciaVoo` INT NOT NULL,
  PRIMARY KEY (`idMovimento`),
  INDEX `fk_Movimento_OcorrenciaVoo1_idx` (`OcorrenciaVoo_idOcorrenciaVoo` ASC),
  CONSTRAINT `fk_Movimento_OcorrenciaVoo1`
    FOREIGN KEY (`OcorrenciaVoo_idOcorrenciaVoo`)
    REFERENCES `sara`.`OcorrenciaVoo` (`idOcorrenciaVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Proprietario` (
  `idProprietario` INT NOT NULL AUTO_INCREMENT,
  `nomeProprietario` VARCHAR(45) NULL,
  PRIMARY KEY (`idProprietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Proprietario_has_TipoAeronave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Proprietario_has_TipoAeronave` (
  `Proprietario_idProprietario` INT NOT NULL,
  `TipoAeronave_idTipoAeronave` INT NOT NULL,
  PRIMARY KEY (`Proprietario_idProprietario`, `TipoAeronave_idTipoAeronave`),
  INDEX `fk_Proprietario_has_TipoAeronave_TipoAeronave1_idx` (`TipoAeronave_idTipoAeronave` ASC),
  INDEX `fk_Proprietario_has_TipoAeronave_Proprietario1_idx` (`Proprietario_idProprietario` ASC),
  CONSTRAINT `fk_Proprietario_has_TipoAeronave_Proprietario1`
    FOREIGN KEY (`Proprietario_idProprietario`)
    REFERENCES `sara`.`Proprietario` (`idProprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proprietario_has_TipoAeronave_TipoAeronave1`
    FOREIGN KEY (`TipoAeronave_idTipoAeronave`)
    REFERENCES `sara`.`TipoAeronave` (`idTipoAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`VooGrupoII`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`VooGrupoII` (
  `idVooGrupoII` INT NOT NULL,
  `Voo_idVoo` INT NOT NULL,
  `nomeComandante` VARCHAR(45) NULL,
  `telefoneComandante` VARCHAR(12) NULL,
  `tempoDeSolo` DECIMAL(10,0) NULL,
  PRIMARY KEY (`idVooGrupoII`),
  CONSTRAINT `idVoo`
    FOREIGN KEY ()
    REFERENCES `sara`.`Voo` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`ProprietarioParticular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`ProprietarioParticular` (
  `idProprietarioParticular` INT NOT NULL AUTO_INCREMENT,
  `Proprietario_idProprietario` INT NOT NULL,
  `querAbastecimento` TINYINT(1) NOT NULL,
  `combustivel` VARCHAR(10) NULL,
  `VooGrupoII_idVooGrupoII` INT NOT NULL,
  PRIMARY KEY (`idProprietarioParticular`),
  INDEX `fk_ProprietarioParticular_VooGrupoII1_idx` (`VooGrupoII_idVooGrupoII` ASC),
  CONSTRAINT `fk_ProprietarioParticular_VooGrupoII1`
    FOREIGN KEY (`VooGrupoII_idVooGrupoII`)
    REFERENCES `sara`.`VooGrupoII` (`idVooGrupoII`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`PreferenciaUsoRecursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`PreferenciaUsoRecursos` (
  `idPreferenciaUsoRecursos` INT NOT NULL,
  `idCiaAérea` INT NOT NULL,
  `idRecurso` INT NOT NULL,
  `PreferenciaUsoRecursoscol` INT NOT NULL,
  PRIMARY KEY (`idPreferenciaUsoRecursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`ProprietarioCiaAerea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`ProprietarioCiaAerea` (
  `idProprietarioCiaAerea` INT NOT NULL AUTO_INCREMENT,
  `Proprietario_idProprietario` INT NOT NULL,
  `sigla` VARCHAR(4) NOT NULL,
  `PreferenciaUsoRecursos_idPreferenciaUsoRecursos` INT NOT NULL,
  PRIMARY KEY (`idProprietarioCiaAerea`, `PreferenciaUsoRecursos_idPreferenciaUsoRecursos`),
  INDEX `fk_ProprietarioCiaAerea_PreferenciaUsoRecursos1_idx` (`PreferenciaUsoRecursos_idPreferenciaUsoRecursos` ASC),
  CONSTRAINT `fk_ProprietarioCiaAerea_PreferenciaUsoRecursos1`
    FOREIGN KEY (`PreferenciaUsoRecursos_idPreferenciaUsoRecursos`)
    REFERENCES `sara`.`PreferenciaUsoRecursos` (`idPreferenciaUsoRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Hotran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Hotran` (
  `idHotran` INT NOT NULL AUTO_INCREMENT,
  `numVooPousa` VARCHAR(5) NULL,
  `numVooDecola` VARCHAR(5) NULL,
  `horarioPrevistoPouso` DATETIME NULL DEFAULT '',
  `horarioPrevistoDecolagem` DATETIME NULL,
  `frequencia` VARCHAR(45) NULL,
  `escalasOrigem` VARCHAR(45) NULL,
  `escalasDestino` VARCHAR(45) NULL,
  `inicioVigencia` DATE NULL,
  `fimVigencia` DATE NULL,
  PRIMARY KEY (`idHotran`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`VooGrupoI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`VooGrupoI` (
  `idVooGrupoI` INT NOT NULL AUTO_INCREMENT,
  `Voo_idVoo` INT NOT NULL,
  `horaConfirmadaPouso` DECIMAL(10,0) NULL,
  `horaConfirmadaDecolagem` DECIMAL(10,0) NULL,
  `Hotran_idHotran` INT NOT NULL,
  PRIMARY KEY (`idVooGrupoI`),
  INDEX `fk_VooGrupoI_Hotran1_idx` (`Hotran_idHotran` ASC),
  CONSTRAINT `fk_VooGrupoI_Hotran1`
    FOREIGN KEY (`Hotran_idHotran`)
    REFERENCES `sara`.`Hotran` (`idHotran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`ProprietarioCiaAerea_has_VooGrupoI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`ProprietarioCiaAerea_has_VooGrupoI` (
  `ProprietarioCiaAerea_idProprietarioCiaAerea` INT NOT NULL,
  `VooGrupoI_idVooGrupoI` INT NOT NULL,
  PRIMARY KEY (`ProprietarioCiaAerea_idProprietarioCiaAerea`, `VooGrupoI_idVooGrupoI`),
  INDEX `fk_ProprietarioCiaAerea_has_VooGrupoI_VooGrupoI1_idx` (`VooGrupoI_idVooGrupoI` ASC),
  INDEX `fk_ProprietarioCiaAerea_has_VooGrupoI_ProprietarioCiaAerea1_idx` (`ProprietarioCiaAerea_idProprietarioCiaAerea` ASC),
  CONSTRAINT `fk_ProprietarioCiaAerea_has_VooGrupoI_ProprietarioCiaAerea1`
    FOREIGN KEY (`ProprietarioCiaAerea_idProprietarioCiaAerea`)
    REFERENCES `sara`.`ProprietarioCiaAerea` (`idProprietarioCiaAerea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProprietarioCiaAerea_has_VooGrupoI_VooGrupoI1`
    FOREIGN KEY (`VooGrupoI_idVooGrupoI`)
    REFERENCES `sara`.`VooGrupoI` (`idVooGrupoI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Recurso` (
  `idRecurso` INT NOT NULL AUTO_INCREMENT,
  `tipoRecurso` VARCHAR(15) NOT NULL,
  `PreferenciaUsoRecursos_idPreferenciaUsoRecursos` INT NOT NULL,
  PRIMARY KEY (`idRecurso`, `PreferenciaUsoRecursos_idPreferenciaUsoRecursos`),
  INDEX `fk_Recurso_PreferenciaUsoRecursos1_idx` (`PreferenciaUsoRecursos_idPreferenciaUsoRecursos` ASC),
  CONSTRAINT `fk_Recurso_PreferenciaUsoRecursos1`
    FOREIGN KEY (`PreferenciaUsoRecursos_idPreferenciaUsoRecursos`)
    REFERENCES `sara`.`PreferenciaUsoRecursos` (`idPreferenciaUsoRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Pista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Pista` (
  `idPista` INT NOT NULL AUTO_INCREMENT,
  `idRecurso` INT NOT NULL,
  `cabeceira` INT NOT NULL,
  `estaEmUso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPista`),
  INDEX `idRecurso_idx` (`idRecurso` ASC),
  CONSTRAINT `idRecurso`
    FOREIGN KEY (`idRecurso`)
    REFERENCES `sara`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`PosicaoPatio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`PosicaoPatio` (
  `idPosicaoPatio` INT NOT NULL AUTO_INCREMENT,
  `idRecurso` INT NOT NULL,
  `nomePosicao` VARCHAR(45) NOT NULL,
  `comprimentoToleravel` FLOAT NULL,
  `envergaduraToleravel` FLOAT NULL,
  `aeronaveCritica` INT NULL,
  `estaEmUso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPosicaoPatio`),
  CONSTRAINT `idRecurso`
    FOREIGN KEY ()
    REFERENCES `sara`.`Recurso` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`PortaoEmbarque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`PortaoEmbarque` (
  `idPortaoEmbarque` INT NOT NULL AUTO_INCREMENT,
  `idRecurso` INT NOT NULL,
  `numeroDoPortao` INT NOT NULL,
  `estaEmUso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPortaoEmbarque`),
  INDEX `fk_idRecurso_idx` (`idRecurso` ASC),
  CONSTRAINT `fk_idRecurso`
    FOREIGN KEY (`idRecurso`)
    REFERENCES `sara`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara`.`EsteiraDeBagagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`EsteiraDeBagagem` (
  `idEsteiraDeBargagem` INT NOT NULL,
  `idRecurso` INT NOT NULL,
  `numeroDaEsteira` INT NOT NULL,
  `estaEmUso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idEsteiraDeBargagem`),
  INDEX `idRecurso_idx` (`idRecurso` ASC),
  CONSTRAINT `idRecurso`
    FOREIGN KEY (`idRecurso`)
    REFERENCES `sara`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`PosicaoHeliponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`PosicaoHeliponto` (
  `idPosicaoHeliponto` INT NOT NULL,
  `idRecurso` INT NOT NULL,
  `numeroDaPosicao` INT NOT NULL,
  `estaEmUso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPosicaoHeliponto`),
  INDEX `idRecurso_idx` (`idRecurso` ASC),
  CONSTRAINT `idRecurso`
    FOREIGN KEY (`idRecurso`)
    REFERENCES `sara`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`OcorrenciaVoo_has_Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`OcorrenciaVoo_has_Recurso` (
  `OcorrenciaVoo_idOcorrenciaVoo` INT NOT NULL,
  `Recurso_idRecurso` INT NOT NULL,
  PRIMARY KEY (`OcorrenciaVoo_idOcorrenciaVoo`, `Recurso_idRecurso`),
  INDEX `fk_OcorrenciaVoo_has_Recurso_Recurso1_idx` (`Recurso_idRecurso` ASC),
  INDEX `fk_OcorrenciaVoo_has_Recurso_OcorrenciaVoo1_idx` (`OcorrenciaVoo_idOcorrenciaVoo` ASC),
  CONSTRAINT `fk_OcorrenciaVoo_has_Recurso_OcorrenciaVoo1`
    FOREIGN KEY (`OcorrenciaVoo_idOcorrenciaVoo`)
    REFERENCES `sara`.`OcorrenciaVoo` (`idOcorrenciaVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OcorrenciaVoo_has_Recurso_Recurso1`
    FOREIGN KEY (`Recurso_idRecurso`)
    REFERENCES `sara`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sara`.`Laercio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara`.`Laercio` (
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB;

CREATE USER 'root' IDENTIFIED BY 'root';

GRANT ALL ON `sara`.* TO 'root';
GRANT SELECT ON TABLE `sara`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER ON TABLE `sara`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `sara`.* TO 'root';
GRANT EXECUTE ON ROUTINE `sara`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
